### ISSUE TITLE
git://github.com/dickeytk/mailboxer.git not found, update readme with correct location for installation

### ISSUE THREAD

**Issue by willfults** [frodefi/rails-messaging#7]
Fetching git://github.com/dickeytk/mailboxer.git
fatal: remote error:
  Repository not found.

**Comment by kabdelhady** [comment]
correct location is at https://github.com/ging/mailboxer

**Comment by i8ramin** [comment]
+1 ... took me some time to figure it out. Simple fix. should be:

```
gem 'messaging', :git => 'git://github.com/frodefi/rails-messaging.git'
gem 'mailboxer', :git => 'git://github.com/ging/mailboxer.git'
```

**Comment by ugisozols** [comment]
I've updated readme. See df7440b2ddf902b76b8f7f8e38653cc2255d7501.
